port: 8317
auth-dir: "/CLIProxyAPI/auth"
remote-management:
  allow-remote: true
  secret-key: ""
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
usage-statistics-enabled: true
logging-to-file: false
ws-auth: true
